# Generated by Django 5.0 on 2025-11-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pet_date_found_alter_pet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='location',
            new_name='last_seen_location',
        ),
        migrations.AddField(
            model_name='pet',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pet',
            name='date_lost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
    ]
