# Generated by Django 5.0 on 2025-11-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_location_pet_last_seen_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
